### ISSUE TITLE
A simple interface to `overrides`

### ISSUE THREAD

**Issue by srid** [srid/haskell-flake#101]
Just an umbrella issue tracking our discussions around this topic.

See https://github.com/srid/haskell-flake/pull/87#issuecomment-1450286992 for a summary on our initial exploration.

**Comment by srid** [comment]
Currently, we write them as follows:

```nix
{
  source-overrides = {
    foo = inputs.fooRepo + /foo;
    qux = "1.2.3"; # Hackage version; yea I just learned that this is already possible.
  };
  overrides = self: super: with pkgs.haskell.lib.compose; {
    qux = lib.pipe super.qux [ dontCheck dontHaddock ];
  };
}
```

This can be made nicer using:

```nix
let
  # A function that enables us to write `foo = [ dontCheck ]` instead of `foo =
  # lib.pipe super.foo [ dontCheck ]` in haskell-flake's `overrides`.
  compilePipe = f: self: super:
    lib.mapAttrs
      (name: value:
        if lib.isList value then
          lib.pipe super.${name} value
        else
          value
      )
      (f self super);
in 
{
  source-overrides = {
    foo = inputs.fooRepo + /foo;
    qux = "1.2.3"; # Hackage version; yea I just learned that this is already possible.
  };
  overrides = self: super: with pkgs.haskell.lib.compose; {
    qux = [ dontCheck dontHaddock ];
  };
}
```

It simply avoids having to specify `lib.pipe super.qux`. This can make visible difference when you have lots of overrides; see https://github.com/nammayatri/nammayatri/pull/47/commits/1374db49425e41698630e419b551b60461e26903 of https://github.com/nammayatri/nammayatri/pull/47. Not sure if worth upstreaming to `haskell-flake` in some form ...

**Comment by srid** [comment]
Here's an idea, and it would also solve the problem of "allowing users to specify default overrides for _all_ local packages _at once_" (to obviate having #146 in haskell-flake).

```nix
{
  overrides = {
    # Overrides for all local packages
    localDefaults = info: [
      dontHaddock
      disableLibraryProfiling
    ] ++ lib.optionals (info.exes != { }) [
      enableSeparateBinOutput
    ];
    # Usual overrides on a per package basis, any package.
    perPackage = _self: _super: {
      aeson = [ dontCheck ];
    };
  };
}
```

The idea here is that the `overrides` option is now *either* an actual overlay function *or* submodule with the structure above. In either case, the merge semantics of the option will use `composeManyExtensions` produce an overlay function, so `imports` functionality should work as before.

**Comment by srid** [comment]
Alternative proposal, which would also solve #82

```nix
{
  basePackages = pkgs.haskellPackages;

  # Configuration for local packages
  localPackages = {
    packages = { foo.root = ./foo; };  # Computed from cabal.project by default
    defaultSettings = { separateBinOutput = true; };  # Applies to all local packages
    settings = { foo.apply = [ dontCheck ]; }; # Per local package settings
  };

  # Settings for any package in the final package set
  settings = [
    # Dependencies that also use haskell-flake
    inputs.shared-kernel.haskellFlakeProjectSettings
    inputs.beckn-gateway.haskellFlakeProjectSettings

    # Local overrides
    {
      cryptostore.from = { hackage = "0.3.0"; };
      passeto.from = { path = inputs.passetto; };
      shared-kernel.from = { drv = pkgs.haskellPackages.shared-kernel; };

      aeson.apply = [ dontCheck ];

      location-updates = {
        separateBinOutput = true;
        libraryProfiling = false;
      };
    }
  ];
}
```

Note a few things:

- `settings` is a _list_ of values.
- Being a list, it enables the user to **explicitly** order their "import" of other haskell-flake projects. Since we don't use the module system imports, we don't suffer from the [arbitrary order](https://github.com/NixOS/nixpkgs/issues/215486) problem
    - Consequently we must add a new option `haskellFlakeProjectSettings` that exports the computed settings overlay
 - The `settings` value is a submodule that will compute to an Haskell overlay. Actual merge will happen _outside_ of the module system (where `finalOverlay` gets defined).
 - We can reuse the same submodule type in `localPackages.{defaultSettings,settings}` (`localPackages.packages` is renamed from current `packages`).

**Comment by srid** [comment]
Actually we can simplify that even further by not doing the `localPackages` change:

```nix
{
  settings = [
    # Dependencies that also use haskell-flake
    inputs.shared-kernel.haskellFlakeProjectModules.settings
    inputs.beckn-gateway.haskellFlakeProjectModules.settings

    # Default overrides for local packages
    (lib.mapAttrs config.haskellProjects.default.packages (name: _: {
      apply = [ enableSeparateBinOutput ];
    }))

    # Project overrides
    {
      cryptostore.from = { hackage = "0.3.0"; };
      passeto.from = { path = inputs.passetto; };
      shared-kernel.from = { drv = pkgs.haskellPackages.shared-kernel; };

      aeson.apply = [ dontCheck ];

      location-updates = {
        separateBinOutput = true;
        libraryProfiling = false;
      };
    }
  ];
}
```

**Comment by ParetoOptimalDev** [comment]
This looks great! I can't wait to try it out and likely update my codebases!

**Comment by srid** [comment]
This is not documented, but it is also possible to add new settings on the project flake: https://github.com/srid/emanote/commit/5b24bd04f94e03afe66ee01da723e4a05d854953
