### ISSUE TITLE
Add a CI check to confirm that `nixpkgs-fmt` was run

### ISSUE THREAD

**Issue by srid** [srid/haskell-flake#115]
Either do it in a simple way or use the treefmt-nix flake-parts module (without bringing that flake input to users of haskell-flake).

**Comment by roberth** [comment]
The inputs concern would be an instance of
 - https://github.com/hercules-ci/flake-parts/issues/119

**Comment by srid** [comment]
I think we can just use https://github.com/cachix/pre-commit-hooks.nix - which gives us a flake check for free.
