### ISSUE TITLE
Unable to use `inputs.package.haskellFlakeProjectModules.output` in consuming flake

### ISSUE THREAD

**Issue by sbh69840** [srid/haskell-flake#118]
Consuming flake's build fails with the following error:
`attribute 'withSystem' missing` , seems to be coming from `default-project-modules.nix:20:19` 

This is happening since this PR: https://github.com/srid/haskell-flake/pull/112/files

Passing `withSystem` as `specialArgs` should fix this.

Should we probably catch such cases using `assert` or have checks for this in CI?

**Comment by srid** [comment]
> Should we probably catch such cases using assert or have checks for this in CI?

This case should be covered in #117
