### ISSUE TITLE
Expose `overrides` in flake

### ISSUE THREAD

**Issue by srid** [srid/haskell-flake#12]
**Rationale**: When I want to use emanote as a library, I want to use its `overrides` (and `source-overrides`) so as to be able to re-use it without replicating it in the local project (that uses emanote as a dependency).

https://github.com/srid/emanote/blob/6f83b857741fb6607716cf97cee3382c7f029180/flake.nix#L43-L51

**Comment by srid** [comment]
Might as well want to expose `modifier`. For https://github.com/srid/tailwind-haskell/blob/0fb8a18b0e770bafc17521836658f31c56e6dfdb/flake.nix#L18-L27

**Comment by srid** [comment]
@locallycompact's https://horizon-haskell.net/ 's overlay could also be exposed in this manner?

**Comment by roberth** [comment]
> https://github.com/srid/emanote/blob/6f83b857741fb6607716cf97cee3382c7f029180/flake.nix#L43-L51

I think these lines could be turned into a small module that can be imported at the project level.

```
      flake.haskellFlakeProjectModules.default =
        ... those lines ...;
      perSystem = { pkgs, system, inputs', self', ... }: {
        haskellProjects.default = {
          imports = [ self.haskellFlakeProjectModules.default ];
```

**Comment by srid** [comment]
Interesting idea. What happens if two modules define the same option, say `buildTools`? Merge, or replace, or ?

**Comment by roberth** [comment]
It's determined by the option `type`.
`attrsOf` and `lazyAttrsOf` will merge; `listOf` appends. Types like `package` and `str` will error out.
`mkForce` and `mkOverride` replace.

**Comment by srid** [comment]
I suppose for `overrides` we ought to create a custom type with `composeExtensions`-based merge semantics, because the default semantics for `types.functions` just calls the functions and merges the results (attrsets): https://github.com/NixOS/nixpkgs/blob/cd71c681ca4e49de4f65e6a45f686f11f3e1b7d3/lib/types.nix#L620-L621

**Comment by srid** [comment]
It just occurred to me that this approach (`imports`) can also solve the problem of decoupling the hardcoded `buildTools`, so that `imports = [ inputs.haskell-flake.defaultSettings ];` for example could set the `buildTools` defaults (and the user can ignore them if they want to start pristine).

**Comment by srid** [comment]
Example:

- Using: https://github.com/srid/haskell-template/pull/85
- Publishing: https://github.com/srid/nixpkgs-140774-workaround
