### ISSUE TITLE
How to set GHC version

### ISSUE THREAD

**Issue by wolverian** [srid/haskell-flake#14]
The `haskellPackages` option at https://github.com/srid/haskell-flake/blob/master/flake-module.nix#L24-L33 says:

> You can effectively select the GHC version here. To get the appropriate value, run:
>     nix-env -f "<nixpkgs>" -qaP -A haskell.compiler

However, I don't know what I should write in my flake.nix - just saying `haskellPackages = haskell.compiler.ghc941` doesn't work for sure. Can you document this a bit more perhaps?

**Comment by srid** [comment]
@wolverian Thanks for the report; I'll update the example. Here's an example meanwhile:

https://github.com/EmaApps/ema/blob/749eb99adaaf1a0152f3e186eab362fcd5f08c9d/flake.nix#L32

**Comment by srid** [comment]
Resolved in 5f04d843713dd829d088bf83c6a8c1cd5356c971

**Comment by wolverian** [comment]
Thank you, this helps me so much. 🙂
