### ISSUE TITLE
Error "cycle detected" when building under specific circumstances

### ISSUE THREAD

**Issue by Eisfunke** [srid/haskell-flake#167]
Under certain circumstances I don't quite understand yet, I'm running into`cycle detected` errors with recent versions of haskell-flake.

I've narrowed it down to the combination of having a `Paths_` (see [here](https://downloads.haskell.org/~ghc/7.0.3/docs/html/Cabal/authors.html#paths-module)) defined under `other-modules` and using `pandoc`under `build-depends` in the cabal file, removing either one "fixes" the problem. I have absolutely no clue what happens there that doesn't seem to happen with the other packages I use.

I've created a minimal reproducing example here: https://git.eisfunke.com/software/experiments/-/tree/haskell-flake-mwe

This seems to be broken since the refactor for modular overrides in commit 996f5c2cdc67285c4990df378976f9dbf26f8401.
`nix build` works in my example with [`github:srid/haskell-flake?rev=74210fa80a49f1b6f67223debdbf1494596ff9f2`](https://github.com/srid/haskell-flake/commit/74210fa80a49f1b6f67223debdbf1494596ff9f2) (the commit before the mentioned one).
But with [`github:srid/haskell-flake?rev=996f5c2cdc67285c4990df378976f9dbf26f8401`](https://github.com/srid/haskell-flake/commit/996f5c2cdc67285c4990df378976f9dbf26f8401) I get:

```
error: cycle detected in build of '/nix/store/3a103gj9pw8c9ibrhmc62r7df3vrqbwi-example-0.1.0.0.drv' in the references of output 'bin' from output 'out'
```

**Comment by roberth** [comment]
It sets `separateBinOutput` to true whenever there's an executable since that commit.
Support for this upstream in Nixpkgs Haskell is spotty, which is why it's opt-in. We probably shouldn't set `separateBinOutput` by default either.

**Comment by srid** [comment]
> I'd suggest to remove the separateBinOutput default from haskell-flake.

Will do.

> Support for this upstream in Nixpkgs Haskell is spotty, which is why it's opt-in.

Is there an upstream issue for this?

**Comment by roberth** [comment]
> upstream issue

Not an issue, but the best context I could find

 - https://github.com/NixOS/nixpkgs/pull/58525#issuecomment-477961077

**Comment by Eisfunke** [comment]
Thank you all for the quick reaction, help and fix! <3 That fixes the problem for me! (although I'm still wondering why this only happened for me with the `Paths_` module *and* the pandoc dependency...)

**Comment by roberth** [comment]
Normally I'd say `nix why-depends`, but I don't think that works for invalid paths.
That said, you might be able to grep it yourself. If it's not a remote build, the outputs are actually added to the store _directory_ temporarily iirc; just not registered in the store db, so they'll be cleaned up during the next store gc.

**Comment by Eisfunke** [comment]
Yeah, while researching the problem I came across the same tip that the paths should be in the store directory, but for some reason they weren't for me (Nix 2.13.3). When I run `nix build` in my MWE above, the output store paths mentioned in the output of`nix log` (`nix path-info` doesn't work for invalid paths) simply don't exist. Maybe it was changed or I've got something peculiar in my Nix config..

But anyway, it works now, so it's not really important ;)
