### ISSUE TITLE
`settings.<name>. cabalFlags` does not work

### ISSUE THREAD

**Issue by ozkutuk** [srid/haskell-flake#177]
I am trying to disable a Cabal flag through `settings`, and looking at the [source](https://github.com/srid/haskell-flake/blob/ab43c9d07efeaaeafd89c0ba371651340b52147d/nix/modules/project/settings/all.nix#L195), I have come up with the following:
```
settings = {
  diagrams-builder = {
    cabalFlags = {
      ps = false;
    };
  };
};
```
However, this results in the following error: 
```
error: A definition for option `impl.cabalFlags."[definition 1-entry 1]".<function body>' is not of type `package'. Definition values:
       - In `/nix/store/gw0j9icfkbqmyis1x3v16mpmp250wvn9-source/nix/modules/project/settings/all.nix': <function>
(use '--show-trace' to show detailed location information)
```
What I essentially want is to have a haskell-flake-equivalent of `diagrams-builder = disableCabalFlag "ps" super.diagrams-builder`. What is the proper way to use the `cabalFlags` option?

**Comment by srid** [comment]
This looks like a bug in the implementation, especially as `enabled` and `disabled` are not even used:

https://github.com/srid/haskell-flake/blob/ab43c9d07efeaaeafd89c0ba371651340b52147d/nix/modules/project/settings/all.nix#L200-L207
