### ISSUE TITLE
Add a `check` for `haskell-language-server`

### ISSUE THREAD

**Issue by srid** [srid/haskell-flake#18]
To sanity check that the project is configured correctly for haskell-language-server to work, we run the following in nix shell:

```
nix develop -i -c haskell-language-server
```

... and check that it successfully exits without any error messages.

The goal of this issue is to have `haskell-flake` automatically add a flake `check` that checks the same. API-wise, it could look like this:

```nix
haskellProjects.foo = {
  checks.haskell-language-server = true;  # True by default if buildTools.haskell-language-server is non-null
};
```

**Comment by srid** [comment]
@roberth Does this ^ make sense? Do you know how something like this (where we run some command in the nix-shell and do it as part of a flake `check`) can be approached?

**Comment by roberth** [comment]
`nix-shell` was originally intended to simulate the build environment, so you could skip the `nix develop` and assume that the build sandbox environment is also sufficiently similar to the nix shell.

You could call `.overrideAttrs` on the devShell to set `src` and some of the other "build-flavored" parameters to turn it into a proper test derivation.

**Comment by srid** [comment]
This also works,

```nix
        checks.hls =
          pkgs.runCommand "hls-check" { buildInputs = self'.devShells.default.nativeBuildInputs; }
            ''
              export HOME=$TMP
              cp -R ${self} $HOME/project
              chmod -R a+w $HOME/project
              pushd $HOME/project

              haskell-language-server > $out
            '';
```
