### ISSUE TITLE
How to override packages with packages from nixpkgs

### ISSUE THREAD

**Issue by MangoIV** [srid/haskell-flake#194]
I want to be able to write 

`packages.fourmolu = pkgs.haskellPackages.fourmolu_0_13_1_0;` 

like I can do with the usual nixpkgs haskell tooling to both improve caching and reuse potential patches.

**Comment by srid** [comment]
You can already do this, see an example here: #192

We should document this though, so keeping the issue open.

**Comment by MangoIV** [comment]
Interesting, thanks!
