### ISSUE TITLE
dangling space in cabal.project causes parser to fail

### ISSUE THREAD

**Issue by MangoIV** [srid/haskell-flake#268]
I just want to leave this here; if people find their cabal.project fail to parse, check if after 
`packages:` there's a space; if there is one, it will fail to parse; remove the space and it will parse according to how it's specified in the docs.

**Comment by srid** [comment]
See https://github.com/srid/haskell-flake/issues/186#issuecomment-1686037616

**Comment by MangoIV** [comment]
oh I'm sorry, I gues I searched for the wrong things :D
