### ISSUE TITLE
devShell to eagerly evaluated? 

### ISSUE THREAD

**Issue by MangoIV** [srid/haskell-flake#270]
to reproduce 
- set `basePackages = pkgs.haskell.packages.ghc90`
- set `devShell.enable = false`

this should eval error: 
>  error: haskell-language-server has dropped support for ghc 9.0 in version 2.4.0.0, please use a newer ghc version or an older nixpkgs version

I'm suspecting that there is some issue with the `devShell` being evaluated to eagerly; the package shouldn't depend on `haskell-language-server` and doesn't try to evaluate/ build it in all other projects

**Comment by srid** [comment]
Does that PR fix it? Because `devShell.tools` already uses `typs.lazyAttrsOf`.

https://github.com/srid/haskell-flake/blob/938888c7ec66d265dda2dad9f4f4ffc9a5a30a78/nix/modules/project/devshell.nix#L19-L20

**Comment by roberth** [comment]
I've tried `hercules-ci-agent`, but got stuck migrating away from its haskell overlay
- https://github.com/srid/haskell-flake/pull/162#issuecomment-1992533135.

**Comment by roberth** [comment]
> `devShell.tools` already uses `typs.lazyAttrsOf`.

According to the trace I got from the haskell-flake `example/`, the culprit was `basePackages`, which was fixed by the PR.
I don't know @MangoIV's project though.
