### ISSUE TITLE
`infinite recursion encountered` when using overrides

### ISSUE THREAD

**Issue by srid** [srid/haskell-flake#4]
Original occurence, including full trace: https://github.com/srid/emanote/pull/290#issuecomment-1141187436

Minimal repro: https://github.com/srid/haskell-template/compare/overrides-bug

**Comment by roberth** [comment]
Could you try chaing `attrsOf` to `lazyAttrsOf` everywhere? https://github.com/hercules-ci/flake-parts/issues/22#issuecomment-1141234923
