### ISSUE TITLE
Add `haskellProjects.foo.finalPackages` to expose the final package set

### ISSUE THREAD

**Issue by srid** [srid/haskell-flake#52]
We want to expose the following as an option:

https://github.com/srid/haskell-flake/blob/54334cfae9bbb73732bbb1437260017044f68d0b/flake-module.nix#L188

This will be useful here: https://github.com/srid/ema-template/pull/45/files#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0L63

Where instead of using `lib.getExe pkgs.haskellPackages.ghcid` (incorrect, because ghcid was overriden) I can instead accurately use `lib.getExe config.haskellPackages.main.finalPackages.ghcid`.

**Comment by roberth** [comment]
`perSystem.haskellProjects.<name>.haskellPackages` would have been a nice name, but that's [taken](https://flake.parts/options/haskell-flake.html#opt-perSystem.haskellProjects._name_.haskellPackages).

How about `haskellProject.<name>.finalPackages`?

You'll have to move the overlay logic from the `perSystem` level to the `haskellProjects.<name>` level to make that work, but I think that's a nice place for that logic to be anyway.

**Comment by srid** [comment]
Sure, `finalPackages` is better. 

But, I'm questioning the naming of `haskellPackages` now. Should we rename it to something else, like `basePackages`? The idea being:

```
basePackages --[ source-overrides; overrides ]--> finalPackages
```

**Comment by roberth** [comment]
Sounds good to me!

**Comment by srid** [comment]
How about this API, where we group overlay-creating settings into a submodule called `packageSet`?

```nix
haskellProjects.foo = {
  devShell.enable = false;
  packageSet = {
    # These settings are applied in that order they are shown here.
    base = pkgs.haskell.packages.ghc944;
    local = {
      mypkg.root = ./.;  # Assumes mypkg.cabal
    };
    source-overrides = { .. }; # Overrides by direct path to source
    overrides = self: super:  { .. };  # Raw Haskell overlay
  };
```

Users can then use `config.haskellPackages.foo.packageSet.final` to access all the packages.

Does it make sense, from API documentation/comprehension/simplicity standpoint, to group the overlay related options like this? Or is it complex? I have a tendency introduce unnecessary abstractions, so it would be good to get some feedback here.

**Comment by maralorn** [comment]
Honestly: I think most interfaces are fine if they are well documented.

From the face of it, I don’t see anything wrong with this one, but problems may only become apparent when using it. Grouping all related options under packageSet will probably be a bit complicated for very simple flakes, but I don’t have a strong opinion about it. Besides packageSet.final I’d like to see a read-only option like packageSet.localPackages or something where one can get all local Haskell packages (to e.g. iterate over) but does not include other packages which could also be in the default packages attribute.

**Comment by srid** [comment]
> I’d like to see a read-only option like packageSet.localPackages or something where one can get all local Haskell packages (to e.g. iterate over) but does not include other packages which could also be in the default packages attribute.

@maralorn With #63 you can access the local packages in the "foo" project using `config.haskellProjects.foo.outputs.packages`.

**Comment by srid** [comment]
Done by #68; rest of discussion to continue in #72
