### ISSUE TITLE
Re-evaluate the structure of `outputs`

### ISSUE THREAD

**Issue by srid** [srid/haskell-flake#74]
I don't think we need this option (added in #63). Here's why:

- `finalPackages` already contains `outputs.packages`
- For `outputs.devShells`, we can expose the devshell in `config.haskellPackages.foo.devShell.drv`
- Likewise, the hls check in `outputs.checks` can be exposed in `config.haskellPackages.foo.devShell.hlsCheck.drv`.

I can't think of a reason to retain `outputs` option in its current form.

**Comment by srid** [comment]
@roberth Let me know what you think.

**Comment by roberth** [comment]
> * `finalPackages` already contains `outputs.packages`

If we're going to maybe optionally disable autowiring into the `perSystem.packages` attribute, we'll want to provide a read-only attribute that only contains the locally defined packages, so the user can set it themselves in they way they want to. That doesn't have to be `outputs.packages`, but could be, say, `localPackages`.

Maybe grouping outputs together helps with reading the docs; not mixing those in with the configurable options. That'd be an argument to move `finalPackages` into the `outputs`.

**Comment by srid** [comment]
> Maybe grouping outputs together helps with reading the docs; not mixing those in with the configurable options. That'd be an argument to move `finalPackages` into the `outputs`.

That's an interesting point. So it would look like:

```nix
{ 
  internal = {
    finalOverlay = ...;
  };
  outputs = {
    finalPackages = { .. };
    localPackages = { .. };  # A subset of `finalPackages`
    devShell = ...;
    hlsCheck = ...;
  };
}
```

Which looks like [the `build` option of treefmt-nix](https://github.com/numtide/treefmt-nix/blob/e9033eca3d7139fd499f310023ddc3bb5abff515/module-options.nix#L85-L86) that @zimbatm came up with.

**Comment by roberth** [comment]
Haven't thought about making `internal` explicit before, interesting! Seems like a good idea.

> `build`

Yeah, this could be somewhat of a pattern.
 - [`treefmt.build`](https://flake.parts/options/treefmt-nix.html#opt-perSystem.treefmt.build.check)
 - NixOS has `system.build`
 - Arion has `out` in [`services.<name>.out`](https://docs.hercules-ci.com/arion/options#_services_name_out_service) and one or two other places
 - flake-parts almost had `outputs`: https://github.com/hercules-ci/flake-parts/issues/67; this almost makes me reconsider...

**Comment by zimbatm** [comment]
`treefmt.build` was directly inspired by NixOS. I was looking for something that is transferable knowledge. But maybe there is an even wider convention that exists. In either case, I'm happy to change and follow your lead on this Robert.
