### ISSUE TITLE
Projects using hpack (not .cabal) cannot be built

### ISSUE THREAD

**Issue by srid** [srid/haskell-flake#85]
Seems to be a regression from ~~#57~~ #42

```
       > No cabal.project file or cabal file matching the default glob './*.cabal' was found.
       > Please create a package description file <pkgname>.cabal or a cabal.project file referencing the packages you want to build.
```

Turns out that the use of `buildFromCabalSdist` is the culprit:

https://github.com/srid/haskell-flake/blob/34641d4508c2ad00d1a5ef5fb592f49bfa9e2770/haskell-project.nix#L36-L50

**Comment by srid** [comment]
@roberth I failed to catch this during the PR review, but do you know what the purpose of `cleanSourceWith` here, is? Because it is not really doing any filtering.

https://github.com/srid/haskell-flake/blob/34641d4508c2ad00d1a5ef5fb592f49bfa9e2770/haskell-project.nix#L38

Also, from your original PR #57:

> This prevents unnecessary rebuilds of packages that haven't really changed, except for a hash that included irrelevant sources.

Does it really do this? Because, [with filtering disabled](https://github.com/srid/haskell-flake/commit/86695baa937a2aae6968c739a5493dee8ecde05c) I can confirm that the `foo` package of https://github.com/srid/haskell-multi-nix does _not_ rebuild when either the top-level README.md or the Haskell source inside of ./bar changes.

Or do you have an example of a specific scenario under which this kind of filtering prevents rebuilds?

**Comment by roberth** [comment]
I think it's supposed to cut the `src` directory from any parent directory contents, and it could serve as an extension point to develop a filter that filters contents within the directory too.

Maybe there's something different about the situation where I used it, such as using a path value instead of string or vice versa. I did set source overrides using paths at somepoint instead of using the default behavior, which is `self.outPath` string-based iirc.

**Comment by srid** [comment]
What would happen if we revert #57 ? Is there a particular scenario where #57 is useful? Just trying to see why we need it -- and if so, at what level -- especially given this bug (#85).

I can see `buildFromCabalSdist` being useful in including only files recognized by cabal, but that doesn't hpack.

**Comment by roberth** [comment]
It probably regresses the rebuilds of packages whose sources are specified with a path value, such as

```
packages.foo.root = ./haskell/foo;
```

I have not confirmed this.



> can see `buildFromCabalSdist` being useful in including only files recognized by cabal, but that doesn't work with hpack

That invocation existed before #57. Did you refer to the intended PR?

**Comment by ParetoOptimalDev** [comment]
> Does it really do this? Because, [with filtering disabled](https://github.com/srid/haskell-flake/commit/86695baa937a2aae6968c739a5493dee8ecde05c) I can confirm that the `foo` package of https://github.com/srid/haskell-multi-nix does _not_ rebuild when either the top-level README.md or the Haskell source inside of ./bar changes.

I've wondered this for a while. I know that there seems to be schism in practice between people who use things like [gitignore.nix](https://github.com/hercules-ci/gitignore.nix) and those that just use the source alone.

My memory of browsing search results was that those who use things like gitignore.nix are in the minority and I thought the change @roberth made would be a good way to give people the desired behavior.

I can't tell you how to reproduce it, but I feel like I've ran into this rebuild issue as well. That's not very actionable though except perhaps to encourage a little more thought or nudge me to go try and reproduce it again if I have time.

**Comment by srid** [comment]
> Did you refer to the intended PR?

Oh, you are right. This issue was introduced in #42 (not 57). "*This catches incomplete release tarballs before they get out.*" - well, that's useful feature to have. So, how do we support projects with `package.yaml` (but no .cabal file) ...

**Comment by srid** [comment]
Workaround:

```nix
{
          basePackages = pkgs.haskellPackages.extend (self: super: {
            # Workaround for https://github.com/srid/haskell-flake/issues/85
            buildFromCabalSdist = x: x;
          });
}
```
> how do we support projects with `package.yaml` (but no .cabal file) ...

Perhaps a project-level option acting as source filter:

```nix
{
   haskellProjects.default = {
     sourceFilter = hp: src: src;  # Default uses hp.buildFromCabalSdist
     packages = { .. };
   };
}
```

But does such an option (`sourceFilter`) have valuable use cases, beyond working around this bug? 

Perhaps we should fix `buildFromCabalSdist` itself to run `hpack` just like `cabal2nix` does.
