### ISSUE TITLE
Remove `pkgFiltered`

### ISSUE THREAD

**Issue by srid** [srid/haskell-flake#88]
contd. from https://github.com/srid/haskell-flake/issues/85#issuecomment-1437429317

@roberth I still don't understand why we need this transformation: https://github.com/srid/haskell-flake/blob/34641d4508c2ad00d1a5ef5fb592f49bfa9e2770/haskell-project.nix#L46-L48

If the code is not needed for any project or has no effect, it should be removed to minimize maintenance.

I'm trying to understand [your comment here](https://github.com/srid/haskell-flake/issues/85#issuecomment-1437483533)

> I think it's supposed to cut the `src` directory from any parent directory contents [..] Maybe there's something different about the situation where I used it

Is there a concrete project example that demonstrates the utility of this code? Without which the project will rebuild unnecessarily? I cannot see it in https://github.com/srid/haskell-multi-nix - so I wonder what I'm missing.

**Comment by srid** [comment]
From [a comment](https://github.com/srid/haskell-flake/issues/85#issuecomment-1438987426) by @ParetoOptimalDev

> I can't tell you how to reproduce it, but I feel like I've ran into this rebuild issue as well. That's not very actionable though except perhaps to encourage a little more thought or nudge me to go try and reproduce it again if I have time.

Yea, it would be good if we can create a reliable repro. I feel uncomfortable having code that I have no understanding of. :-)

**Comment by roberth** [comment]
I've played around with this a bit and couldn't find a reproducer despite a couple of variations of passing the source:
 - path string
 - path value
 - source attrset from `cleanSourceWith`

None of these variations reproduced the problem.

You have my permission to remove the extra filter. If rebuilds reappear, we'll have a reproducer.
